### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by s-muntazir** [kroodle/cordova-plugin-heartbeat#1]
Hi

I just installed this plugin on ionic 3 and tried on android. It starts the camera and flash but then it gives an error message “package not found “

Could you please help

**Comment by koenoe** [comment]
Thanks for your interest in this plugin.
In order to use it you'll need a licensed library from [Happitech](http://happitech.com/)

**Comment by s-muntazir** [comment]
Thanks koenoe

I looked at that website but there is no way to buy the licenced version .

How do i get the license version of happitech

**Comment by koenoe** [comment]
You’ll have to contact them. It’s not possible to buy a license directly via their website.
